In [8]:
import pandas as pd
df = pd.read_csv("heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [9]:
df.ChestPainType.unique()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['ChestPainType'] = le.fit_transform(df[['ChestPainType']])
df['RestingECG'] = le.fit_transform(df[['RestingECG']])
df['ST_Slope'] = le.fit_transform(df[['ST_Slope']])
df['Sex'] = le.fit_transform(df[['ST_Slope']])
df['ExerciseAngina'] = le.fit_transform(df[['ST_Slope']])
df

C:\Users\pushk\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pushk\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pushk\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pushk\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\pushk\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,2,1,140,289,0,1,172,2,0.0,2,0
1,49,1,2,160,180,0,1,156,1,1.0,1,1
2,37,2,1,130,283,0,2,98,2,0.0,2,0
3,48,1,0,138,214,0,1,108,1,1.5,1,1
4,54,2,2,150,195,0,1,122,2,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,1,1.2,1,1
914,68,1,0,144,193,1,1,141,1,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,1,1,130,236,0,0,174,1,0.0,1,1
917,38,2,2,138,175,0,1,173,2,0.0,2,0

In [10]:
from sklearn.preprocessing import StandardScaler
y = df['HeartDisease']
X = df.drop(['HeartDisease'], axis='columns')
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [11]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y)
modelsvc = SVC()
modelsvc.fit(X_train,y_train)
modelsvc.score(X_test,y_test)

0.7652173913043478

In [13]:
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score

bag_model = BaggingClassifier(
    estimator=SVC(), 
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model, X, y, cv=5)
scores.mean()

0.6873129009265859

In [14]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8173913043478261

In [15]:
bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(), 
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)
scores1 = cross_val_score(bag_model, X, y, cv=5)
scores1.mean()

0.790775718698028