In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("metadata.csv")
df

      Unnamed: 0                  image   class format mode          shape
0              0         Cancer (1).jpg   tumor   JPEG  RGB  (512, 512, 3)
1              1         Cancer (1).png   tumor    PNG    L     (300, 240)
2              2         Cancer (1).tif   tumor   TIFF  RGB  (256, 256, 3)
3              3        Cancer (10).jpg   tumor   JPEG  RGB  (512, 512, 3)
4              4        Cancer (10).tif   tumor   TIFF  RGB  (256, 256, 3)
...          ...                    ...     ...    ...  ...            ...
4595        4595  Not Cancer  (995).jpg  normal   JPEG  RGB  (168, 300, 3)
4596        4596  Not Cancer  (996).jpg  normal   JPEG  RGB  (509, 452, 3)
4597        4597  Not Cancer  (997).jpg  normal   JPEG  RGB  (197, 177, 3)
4598        4598  Not Cancer  (998).jpg  normal   JPEG  RGB  (217, 232, 3)
4599        4599  Not Cancer  (999).jpg  normal   JPEG  RGB  (221, 228, 3)

[4600 rows x 6 columns]

In [19]:
df['class'].unique()

array(['tumor', 'normal'], dtype=object)

In [20]:
df = df.drop(['format','mode'], axis='columns')
df

      Unnamed: 0                  image   class          shape
0              0         Cancer (1).jpg   tumor  (512, 512, 3)
1              1         Cancer (1).png   tumor     (300, 240)
2              2         Cancer (1).tif   tumor  (256, 256, 3)
3              3        Cancer (10).jpg   tumor  (512, 512, 3)
4              4        Cancer (10).tif   tumor  (256, 256, 3)
...          ...                    ...     ...            ...
4595        4595  Not Cancer  (995).jpg  normal  (168, 300, 3)
4596        4596  Not Cancer  (996).jpg  normal  (509, 452, 3)
4597        4597  Not Cancer  (997).jpg  normal  (197, 177, 3)
4598        4598  Not Cancer  (998).jpg  normal  (217, 232, 3)
4599        4599  Not Cancer  (999).jpg  normal  (221, 228, 3)

[4600 rows x 4 columns]